framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection:
        enabled: true
    session:
        enabled: true
        cookie_samesite: lax
        cookie_secure: auto

    # Ces options doivent être au niveau de "framework" et non dans "framework.session"
    trusted_proxies: ['127.0.0.1', '::1']
    trusted_headers: ['X-Forwarded-Proto']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
